# Site settings
title: 啊？还要给博客想个名字？
SEOTitle: 邱陈程的博客 | Pinkuburu's Blog
header-img: img/home-bg.jpg
email: 1012803704@qq.com
description: "关于Unity开发，游戏开发，Unreal，虚幻4，美术，手绘，3D美术，渲染技术"
keyword: "邱陈程, pinkuburu, Unity, C#"
url: "https://omgnn.com"              # your host, for absolute URL 
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     acghongniu
#zhihu_username:     he-hong-niu-you-li-liang
github_username:    Pinkuburu
#twitter_username:  PinkuburuCC
#facebook_username:  profile.php?id=100003134645551
linkedin_username:  陈程-邱-9ab8a4a3

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "东一榔头西一棒槌，三分钟热度学东西<br>喜欢整些有的没的"
sidebar-avatar: /img/avatar-qcc.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
  ]
