// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.01 Use regions to block out Events and/or the player from\r\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"2","All Restrict":"0","Player Allow":"0","Event Allow":"0","All Allow":"0"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}}
];
